name: gride
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  code_editor: ^1.3.2
  cupertino_icons: ^1.0.2
  pluto_code_editor: ^0.1.1
  flutter_riverpod: ^2.3.2
  google_fonts: ^4.0.3
  sizer: ^2.0.15
  window_manager: ^0.3.2
  responsive_framework: ^1.0.0
  go_router: ^7.0.0

dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  image_path: "assets/images/app-logo.png"
  android: false
  ios: true
  web: true
  remove_alpha_ios: true
