// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWSltb-qSJ2aTZeNzsknozbIVyom9xPhg',
    appId: '1:899141272370:web:8bbf3d5c70530e01164d2b',
    messagingSenderId: '899141272370',
    projectId: 'gride-af97e',
    authDomain: 'gride-af97e.firebaseapp.com',
    storageBucket: 'gride-af97e.appspot.com',
    measurementId: 'G-21R6WRG099',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_B__cK3e4ixKmmoOnC4nkxSynS0eXG4',
    appId: '1:899141272370:android:fae04ee0b9284760164d2b',
    messagingSenderId: '899141272370',
    projectId: 'gride-af97e',
    storageBucket: 'gride-af97e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAM0jAre1D0HxMb81mmIRlG_tpDqy0tVA',
    appId: '1:899141272370:ios:30ac84b0fe29e7b6164d2b',
    messagingSenderId: '899141272370',
    projectId: 'gride-af97e',
    storageBucket: 'gride-af97e.appspot.com',
    iosClientId: '899141272370-iveu301656q4n357udk5ev59ktskavg1.apps.googleusercontent.com',
    iosBundleId: 'io.gride.gride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAM0jAre1D0HxMb81mmIRlG_tpDqy0tVA',
    appId: '1:899141272370:ios:30ac84b0fe29e7b6164d2b',
    messagingSenderId: '899141272370',
    projectId: 'gride-af97e',
    storageBucket: 'gride-af97e.appspot.com',
    iosClientId: '899141272370-iveu301656q4n357udk5ev59ktskavg1.apps.googleusercontent.com',
    iosBundleId: 'io.gride.gride',
  );
}
